version = "0.2"
ignorePaths = [
  ".github/",
  "schema/",
  "docs/",
  "*.typ",
  "*.toml.json",
  "justfile",
]
words = [
  "nabcv",
  "fontawesome",
  "toml",
  "typst",
  "xrsl",
  "Resul",
  "resulal",
  "ppi",
  "bumpversion",
  "utpm",
  "tidy",
  "cspell",
  "justfile",
  "typstyle",
  "tombi",
  "acadennial",
  "johndoe",
  "janesmith",
  "yourhandle",
  "acqui",
  "postmortems",
  "Alphabetising",
  "Tetris",
  "Specialised",
  "apologising",
  "pytest",
  "offence",
  "realising",
  "Hackathon",
  "Standups",
  "juin",
  "juil",
  "août",
]
