name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: extractions/setup-just@v3
        with:
          just-version: 1.46.0

      - uses: typst-community/setup-typst@v4
        with:
          typst-version: "latest"

      - name: Install fonts
        run: sudo apt-get install -y fonts-ibm-plex

      - name: Install cspell
        run: npm install -g cspell

      - uses: j178/prek-action@v1
        with:
          install-only: true
      - run: just prek-ci
      - run: just spell
      - run: just build
        env:
          TYPST_FONT_PATHS: /home/runner/.local/share/typst/packages
